#!/usr/bin/env bash
# This script installs and configures HAproxy

sudo apt update
sudo apt install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 173217-web-01 54.166.146.161:80 check\n\tserver 173217-web-02 54.157.189.14:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
